"""create transactions

Revision ID: 2de10033cc1c
Revises:
Create Date: 2026-06-13 20:20:53.628910
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2de10033cc1c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("occurred_on", sa.Date(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("usd_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("fx_rate", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("fx_rate_type", sa.String(length=20), nullable=True),
        sa.Column("fx_rate_as_of", sa.DateTime(timezone=True), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("payment_method", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("recurring", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("counts_toward_monotributo", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_transactions_occurred_on", "transactions", ["occurred_on"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transactions_occurred_on", table_name="transactions")
    op.drop_table("transactions")
    # ### end Alembic commands ###
