"""Frozen Pydantic commands for the account aggregate (ADR-122, ADR-130, ADR-134).

Commands are immutable, boundary-agnostic requests to change state. They carry
input fields only: ``id``, ``created_at`` and ``updated_at`` are server-managed
and generated by the handler, never supplied by the caller. Money is ``Decimal``
(ADR-025); ``currency`` reuses the domain value object so the contract stays
aligned with the aggregate. An account is a per-currency leaf under an institution
(ADR-134), so a create carries the owning ``institution_id``. ``user_id`` is the
authenticated owner the entrypoint stamps before dispatch so every account is
owned from creation (ADR-130).
"""

from __future__ import annotations

from decimal import Decimal
from uuid import UUID

from margen_api.domain.messages import Command


class CreateAccount(Command):
    """Request to create a new account under an institution (ADR-130, ADR-134).

    The handler verifies ``institution_id`` is one the caller owns (ADR-130),
    generates ``id``, ``created_at`` and ``updated_at`` and applies domain
    invariants via the aggregate (known currency). ``opening_balance`` is the
    native-currency balance before any transaction and may be zero or negative
    (e.g. a card account); it defaults to ``0`` (ADR-124).
    """

    user_id: str
    institution_id: UUID
    currency: str = "ARS"
    opening_balance: Decimal = Decimal(0)


class UpdateAccount(Command):
    """Request to patch an existing account (ADR-122, ADR-130, ADR-134).

    Every mutable field is optional; ``None`` means "leave unchanged". The handler
    loads the aggregate by ``id`` **scoped to ``user_id``** (a foreign owner's id is
    not found, ADR-111), applies the present fields, re-runs invariants, and
    refreshes ``updated_at``. When ``institution_id`` is (re)assigned the handler
    re-checks ownership (ADR-130). ``user_id`` is the authenticated owner the
    entrypoint sets before dispatch; ownership is never patchable.
    """

    id: UUID
    user_id: str
    institution_id: UUID | None = None
    currency: str | None = None
    opening_balance: Decimal | None = None
