"""Frozen Pydantic commands for the account aggregate (ADR-122, ADR-130).

Commands are immutable, boundary-agnostic requests to change state. They carry
input fields only: ``id``, ``created_at`` and ``updated_at`` are server-managed
and generated by the handler, never supplied by the caller. Money is ``Decimal``
(ADR-025); ``type``/``currency`` reuse the domain value objects so the contract
stays aligned with the aggregate. ``user_id`` is the authenticated owner the
entrypoint stamps before dispatch so every account is owned from creation
(ADR-130).
"""

from __future__ import annotations

from decimal import Decimal
from uuid import UUID

from pydantic import Field

from margen_api.domain.messages import Command
from margen_api.domain.models.value_objects import AccountType, Currency


class CreateAccount(Command):
    """Request to create a new account (ADR-122, ADR-130).

    The handler generates ``id``, ``created_at`` and ``updated_at`` and applies
    domain invariants via the aggregate (non-empty name, known type/currency).
    ``opening_balance`` is the native-currency balance before any transaction and
    may be zero or negative (e.g. a card account); it defaults to ``0`` (ADR-124).
    """

    user_id: str
    name: str = Field(min_length=1)
    type: AccountType
    currency: Currency = Currency.ARS
    opening_balance: Decimal = Decimal(0)


class UpdateAccount(Command):
    """Request to patch an existing account (ADR-122, ADR-130).

    Every mutable field is optional; ``None`` means "leave unchanged". The handler
    loads the aggregate by ``id`` **scoped to ``user_id``** (a foreign owner's id is
    not found, ADR-111), applies the present fields, re-runs invariants, and
    refreshes ``updated_at``. ``user_id`` is the authenticated owner the entrypoint
    sets before dispatch; ownership is never patchable.
    """

    id: UUID
    user_id: str
    name: str | None = Field(default=None, min_length=1)
    type: AccountType | None = None
    currency: Currency | None = None
    opening_balance: Decimal | None = None
