"""Frozen Pydantic commands for the budget aggregate (ADR-125, ADR-130).

Commands are immutable, boundary-agnostic requests to change state. They carry
input fields only: ``id``, ``created_at`` and ``updated_at`` are server-managed and
generated by the handler, never supplied by the caller. Money is ``Decimal``
(ADR-025); ``currency`` defaults to ARS (the MVP target currency, ADR-125 currency
note). ``period`` is the budget month as a ``date`` — the entrypoint parses the
``YYYY-MM`` month into the first day before dispatch, mirroring the summaries
month-navigator parsing (ADR-040). ``user_id`` is the authenticated owner the
entrypoint stamps before dispatch so every budget is owned from creation (ADR-130).
"""

from __future__ import annotations

from datetime import date
from decimal import Decimal

from margen_api.domain.messages import Command


class UpsertBudget(Command):
    """Request to set (insert or replace) a category's monthly target (ADR-125, ADR-130).

    Upsert semantics: a budget is unique per ``(user_id, category, period)``
    (ADR-125), so dispatching this for a category/month that already has a target
    *replaces* the amount rather than creating a duplicate. The handler resolves the
    existing row scoped to ``user_id`` (ADR-130), generates ``id``/timestamps on a
    fresh insert, and applies domain invariants via the aggregate (known currency,
    period normalized to the first of the month). The target is stamped with
    ``user_id`` so it is owned from creation (ADR-130).
    """

    user_id: str
    category: str
    period: date
    amount: Decimal
    currency: str = "ARS"


class ClearBudget(Command):
    """Request to clear a category's target for a month (ADR-125, ADR-130).

    Optional convenience to unset a target so the category reads back with a ``null``
    target. The handler resolves the row scoped to ``user_id`` (ADR-130) and deletes
    it; clearing an absent target is a no-op (idempotent), so the boundary answers
    ``204`` either way.
    """

    user_id: str
    category: str
    period: date
