"""Frozen Pydantic commands for the institution aggregate (ADR-130, ADR-134).

Commands are immutable, boundary-agnostic requests to change state. They carry
input fields only: ``id``, ``created_at`` and ``updated_at`` are server-managed
and generated by the handler, never supplied by the caller. ``type`` reuses the
domain value object so the contract stays aligned with the aggregate. ``user_id``
is the authenticated owner the entrypoint stamps before dispatch so every
institution is owned from creation (ADR-130).
"""

from __future__ import annotations

from uuid import UUID

from pydantic import Field

from margen_api.domain.messages import Command
from margen_api.domain.models.value_objects import InstitutionType


class CreateInstitution(Command):
    """Request to create a new institution (ADR-130, ADR-134).

    The handler generates ``id``, ``created_at`` and ``updated_at`` and applies
    domain invariants via the aggregate (non-empty name, known type).
    """

    user_id: str
    name: str = Field(min_length=1)
    type: InstitutionType = InstitutionType.BANK


class UpdateInstitution(Command):
    """Request to patch an existing institution (ADR-130, ADR-134).

    Every mutable field is optional; ``None`` means "leave unchanged". The handler
    loads the aggregate by ``id`` **scoped to ``user_id``** (a foreign owner's id is
    not found, ADR-111), applies the present fields, re-runs invariants, and
    refreshes ``updated_at``. ``user_id`` is the authenticated owner the entrypoint
    sets before dispatch; ownership is never patchable.
    """

    id: UUID
    user_id: str
    name: str | None = Field(default=None, min_length=1)
    type: InstitutionType | None = None
