"""Frozen Pydantic commands for the receivables cluster (ADR-204, ADR-206, ADR-130).

Commands are immutable, boundary-agnostic requests to change state. They carry input
fields only: ``id``, ``created_at`` and identity of created rows are server-managed and
generated by the handler, never supplied by the caller (ADR-026). Money is ``Decimal``
(ADR-025), ARS-only for v1. ``user_id`` is the authenticated owner the entrypoint stamps
before dispatch so every person — and, through it, every item and payment — is owned from
creation (ADR-130).

The :class:`Person` is the aggregate root; items and payments key off it, so their write
commands carry the ``person_id`` (or the item/person ownership is re-resolved by the
handler). A payment is recorded together with its allocations across items in one command
so the settlement is atomic (ADR-206).
"""

from __future__ import annotations

from datetime import date
from decimal import Decimal
from uuid import UUID

from pydantic import Field

from margen_api.domain.messages import Command, Message
from margen_api.domain.models.value_objects import PaymentSource


class CreatePerson(Command):
    """Request to create a new debtor the owner tracks receivables against (ADR-204, ADR-130).

    The handler generates ``id`` and ``created_at`` and applies the domain invariant
    (non-empty name) via the aggregate.
    """

    user_id: str
    name: str = Field(min_length=1)


class RenamePerson(Command):
    """Request to rename an existing person (ADR-204, ADR-130).

    The handler loads the person by ``id`` **scoped to ``user_id``** (a foreign owner's id
    is not found, ADR-111), applies the new name and re-runs the invariant. Ownership,
    identity and ``created_at`` are never changed.
    """

    id: UUID
    user_id: str
    name: str = Field(min_length=1)


class DeletePerson(Command):
    """Request to delete a person by identity (ADR-204, ADR-130).

    The handler scopes the delete by ``user_id`` so a cross-tenant delete removes nothing
    and surfaces a not-found (404, ADR-111). The database cascades the person's items and
    payments (and their allocations) away (ADR-208).
    """

    id: UUID
    user_id: str


class AddReceivableItem(Command):
    """Request to add an itemized debt to one of the owner's people (ADR-204, ADR-130).

    The handler verifies the person exists for the owner (else 404, ADR-111), then
    generates ``id`` and ``created_at`` and applies the domain invariant (positive
    amount). ``detail`` is the optional free-text justification, trimmed to ``None`` when
    blank by the aggregate.
    """

    user_id: str
    person_id: UUID
    occurred_on: date
    amount: Decimal = Field(gt=Decimal(0))
    detail: str | None = None


class EditReceivableItem(Command):
    """Request to patch an existing receivable item (ADR-204, ADR-130).

    Every mutable field is optional; ``None`` means "leave unchanged". The handler loads
    the item by ``id`` **scoped to the owner** (through the item's person, ADR-111),
    applies the present fields, and re-runs invariants. The item's ``person_id``,
    identity and ``created_at`` are never changed.
    """

    id: UUID
    user_id: str
    occurred_on: date | None = None
    amount: Decimal | None = Field(default=None, gt=Decimal(0))
    detail: str | None = None


class DeleteReceivableItem(Command):
    """Request to delete a receivable item by identity (ADR-204, ADR-130).

    The handler scopes the delete to the owner (through the item's person) so a
    cross-tenant delete removes nothing and surfaces a not-found (404, ADR-111). The
    database cascades the item's allocations away (ADR-208).
    """

    id: UUID
    user_id: str


class AllocationInput(Message):
    """One slice of a payment applied to a specific item, as supplied by the caller (ADR-206).

    A nested value inside :class:`RecordReceivablePayment`; the handler turns each into a
    :class:`~margen_api.domain.models.receivable.ReceivableAllocation` once the payment's
    identity exists. ``amount`` is a positive ARS magnitude (ADR-025).
    """

    item_id: UUID
    amount: Decimal = Field(gt=Decimal(0))


class RecordReceivablePayment(Command):
    """Request to record an incoming payback and allocate it across items (ADR-204, ADR-206).

    The handler verifies the person exists for the owner (else 404), verifies every
    allocation targets one of that person's items (else 404), and enforces the two
    settlement rules of ADR-206:

    * The allocations may not sum to more than the payment's own ``amount`` — a true
      invariant violation (``422``).
    * When the allocations would drive the person's outstanding balance below zero, the
      handler raises an overpayment **warning** unless ``allow_overpayment`` is set, so
      the API layer can confirm the credit with the user rather than silently clamping or
      going negative.

    ``source``/``matched_income_transaction_id`` record whether the payback was typed by
    hand (``manual``) or confirmed from a fuzzy income match (``matched_income``, ADR-207);
    the confirm flow that produces the latter lives in a separate slice.
    """

    user_id: str
    person_id: UUID
    occurred_on: date
    amount: Decimal = Field(gt=Decimal(0))
    allocations: tuple[AllocationInput, ...] = Field(min_length=1)
    source: PaymentSource = PaymentSource.MANUAL
    matched_income_transaction_id: UUID | None = None
    allow_overpayment: bool = False
