"""Frozen Pydantic commands for the transaction aggregate (ADR-028, ADR 0011).

Commands are immutable, boundary-agnostic requests to change state. They carry
input fields only: ``id``, ``created_at`` and ``updated_at`` are server-managed
and generated by the handler, never supplied by the caller. Money is ``Decimal``
(ADR-025); ``kind``/``currency`` reuse the domain value objects so the contract
stays aligned with the aggregate.
"""

from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from uuid import UUID

from pydantic import Field

from margen_api.domain.messages import Command
from margen_api.domain.models.value_objects import Currency, FxRateType, Kind


class CreateTransaction(Command):
    """Request to record a new transaction.

    The handler generates ``id``, ``created_at`` and ``updated_at`` and applies
    domain invariants via the aggregate (e.g. positive amount, monotributo
    counting forced ``False`` for expense). USD rows without a rate are accepted.
    """

    occurred_on: date
    name: str = Field(min_length=1)
    kind: Kind
    amount: Decimal = Field(gt=Decimal(0))
    currency: Currency = Currency.ARS
    usd_amount: Decimal | None = None
    fx_rate: Decimal | None = None
    fx_rate_type: FxRateType | None = None
    fx_rate_as_of: datetime | None = None
    category: str | None = None
    payment_method: str | None = None
    notes: str | None = None
    recurring: bool = False
    counts_toward_monotributo: bool = False


class UpdateTransaction(Command):
    """Request to patch an existing transaction.

    Every mutable field is optional; ``None`` means "leave unchanged". The handler
    loads the aggregate by ``id``, applies the present fields, re-runs invariants,
    and refreshes ``updated_at``.
    """

    id: UUID
    occurred_on: date | None = None
    name: str | None = Field(default=None, min_length=1)
    kind: Kind | None = None
    amount: Decimal | None = Field(default=None, gt=Decimal(0))
    currency: Currency | None = None
    usd_amount: Decimal | None = None
    fx_rate: Decimal | None = None
    fx_rate_type: FxRateType | None = None
    fx_rate_as_of: datetime | None = None
    category: str | None = None
    payment_method: str | None = None
    notes: str | None = None
    recurring: bool | None = None
    counts_toward_monotributo: bool | None = None


class DeleteTransaction(Command):
    """Request to delete a transaction by identity."""

    id: UUID
