"""Frozen Pydantic commands for the transaction aggregate (ADR-028, ADR 0011).

Commands are immutable, boundary-agnostic requests to change state. They carry
input fields only: ``id``, ``created_at`` and ``updated_at`` are server-managed
and generated by the handler, never supplied by the caller. Money is ``Decimal``
(ADR-025); ``kind``/``currency`` reuse the domain value objects so the contract
stays aligned with the aggregate.
"""

from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from uuid import UUID

from pydantic import Field

from margen_api.domain.messages import Command, Message
from margen_api.domain.models.value_objects import Currency, FxRateType, Kind, RecurringCadence


class TransactionDocumentPayload(Message):
    """Optional invoice document to store alongside a created transaction (ADR-070).

    Carries the uploaded PDF and its import metadata so the create handler can
    persist it as a 1:1 side record through the ``DocumentStore`` port in the same
    unit of work (ADR-071). The bytes travel as raw :class:`bytes` here — the
    entrypoint decodes the base64 wire value at the boundary so the bytes never
    enter the transaction aggregate. The fiscal natural-key fields back the
    advisory dedupe check; all are optional because a text-only or malformed
    invoice may not yield every field (ADR-071). Money is ``Decimal`` (ADR-025).

    Attributes:
        pdf_bytes: The original uploaded PDF bytes.
        content_type: The MIME type of the upload (``application/pdf``).
        byte_size: The PDF size in bytes.
        extracted_text: Parsed PDF text, or ``None`` when none was extracted.
        qr_json: Decoded AFIP QR JSON payload, or ``None`` when absent.
        emisor_cuit: Issuer CUIT from the natural key, or ``None``.
        pto_vta: Point of sale from the natural key, or ``None``.
        tipo_cmp: Voucher type code from the natural key, or ``None``.
        nro_cmp: Voucher number from the natural key, or ``None``.
        cae: Electronic authorization code, or ``None``.
        fecha: Invoice date, or ``None``.
        importe: Invoice total in its original currency, or ``None``.
        moneda: Currency code (e.g. ``ARS``), or ``None``.
        ctz: Exchange rate declared on the invoice, or ``None``.
    """

    pdf_bytes: bytes
    content_type: str
    byte_size: int
    extracted_text: str | None = None
    qr_json: dict | None = None
    emisor_cuit: str | None = None
    pto_vta: str | None = None
    tipo_cmp: str | None = None
    nro_cmp: str | None = None
    cae: str | None = None
    fecha: date | None = None
    importe: Decimal | None = None
    moneda: str | None = None
    ctz: Decimal | None = None


class CreateTransaction(Command):
    """Request to record a new transaction.

    The handler generates ``id``, ``created_at`` and ``updated_at`` and applies
    domain invariants via the aggregate (e.g. positive amount, monotributo
    counting forced ``False`` for expense). USD rows without a rate are accepted.
    An optional ``document`` attaches the imported invoice PDF, stored as a side
    record in the same unit of work (ADR-070, ADR-071); omitting it leaves the
    existing create contract unchanged. ``user_id`` is the authenticated owner the
    entrypoint sets from ``AuthUser.id`` before dispatch (ADR-108); the handler
    stores it on the inserted row so the transaction is owned from creation.

    For ``kind='reimbursement'`` (ADR-158) the optional ``offsets_transaction_id``
    links the payback to the EXPENSE it reduces (ADR-159). The handler validates
    that the target exists, is owned by the same user, and is an EXPENSE (ADR-130)
    before persisting; the domain forces the link ``None`` for every other kind.
    """

    occurred_on: date
    name: str = Field(min_length=1)
    kind: Kind
    amount: Decimal = Field(gt=Decimal(0))
    currency: Currency = Currency.ARS
    usd_amount: Decimal | None = None
    fx_rate: Decimal | None = None
    fx_source: str | None = None
    fx_rate_type: FxRateType | None = None
    fx_rate_as_of: datetime | None = None
    category: str | None = None
    payment_method: str | None = None
    card: str | None = None
    notes: str | None = None
    recurring: bool = False
    recurring_cadence: RecurringCadence | None = None
    installments_total: int | None = None
    installments_index: int | None = None
    counts_toward_monotributo: bool = False
    account_id: UUID | None = None
    offsets_transaction_id: UUID | None = None
    user_id: str
    document: TransactionDocumentPayload | None = None


class UpdateTransaction(Command):
    """Request to patch an existing transaction.

    Every mutable field is optional; ``None`` means "leave unchanged". The handler
    loads the aggregate by ``id`` **scoped to ``user_id``** (a foreign owner's id is
    not found, ADR-108/ADR-111), applies the present fields, re-runs invariants, and
    refreshes ``updated_at``. ``user_id`` is the authenticated owner the entrypoint
    sets from ``AuthUser.id`` before dispatch.
    """

    id: UUID
    user_id: str
    occurred_on: date | None = None
    name: str | None = Field(default=None, min_length=1)
    kind: Kind | None = None
    amount: Decimal | None = Field(default=None, gt=Decimal(0))
    currency: Currency | None = None
    usd_amount: Decimal | None = None
    fx_rate: Decimal | None = None
    fx_source: str | None = None
    fx_rate_type: FxRateType | None = None
    fx_rate_as_of: datetime | None = None
    category: str | None = None
    payment_method: str | None = None
    notes: str | None = None
    recurring: bool | None = None
    recurring_cadence: RecurringCadence | None = None
    installments_total: int | None = None
    installments_index: int | None = None
    counts_toward_monotributo: bool | None = None
    account_id: UUID | None = None


class SetTransactionFxSnapshot(Command):
    """Request to set or replace the FX snapshot on an existing transaction (ADR-148, ADR-149).

    Powers the client import rate-fill step and the one-time historical backfill
    (ADR-149/150): the client supplies the ARS-per-1-USD ``fx_rate`` and its
    ``fx_source`` provenance, and the handler re-materializes ``usd_amount`` as pure
    arithmetic (``round(amount ÷ fx_rate, 2)``, ADR-148) — the backend never calls an
    FX feed. The aggregate is loaded by ``id`` **scoped to ``user_id``** so a foreign
    owner's id is not found (a cross-tenant snapshot is a 404, ADR-108/ADR-111).
    ``user_id`` is the authenticated owner the entrypoint sets from ``AuthUser.id``
    before dispatch.

    Attributes:
        id: The transaction whose snapshot is being set.
        user_id: The authenticated owner the load/persist is scoped to.
        fx_rate: The ARS-per-1-USD rate the client captured (ADR-149).
        fx_source: The rate's provenance, e.g. ``'bolsa'`` / ``'mep'`` / ``'oficial'``
            / ``'manual'`` / ``'backfill'`` (ADR-148); optional.
    """

    id: UUID
    user_id: str
    fx_rate: Decimal
    fx_source: str | None = None


class DeleteTransaction(Command):
    """Request to delete a transaction by identity.

    ``user_id`` is the authenticated owner the entrypoint sets from ``AuthUser.id``
    before dispatch; the handler scopes the delete by it so a cross-tenant delete
    removes nothing and surfaces a not-found (404, ADR-108/ADR-111).
    """

    id: UUID
    user_id: str
