"""Frozen Pydantic commands for the transfer aggregate (ADR-135, ADR-130).

Commands are immutable, boundary-agnostic requests to change state. They carry
input fields only: ``id``, ``created_at`` and ``updated_at`` are server-managed and
generated by the handler, never supplied by the caller. Money is ``Decimal``
(ADR-025). A transfer moves money between two of the caller's accounts (ADR-135);
optional ``fees`` ride on the create so each fee can be recorded as an expense
transaction in the same unit of work. ``user_id`` is the authenticated owner the
entrypoint stamps before dispatch so every transfer is owned from creation (ADR-130).
"""

from __future__ import annotations

from datetime import date
from decimal import Decimal
from uuid import UUID

from pydantic import Field

from margen_api.domain.messages import Command, Message


class TransferFeeInput(Message):
    """One fee charged on a transfer, recorded as an expense transaction (ADR-135).

    Each fee becomes a separate ``kind=expense`` transaction in the "Fees" category
    on ``account_id``, in that account's native currency, created atomically with the
    transfer (ADR-135). All fee accounts must belong to the caller (ADR-130).

    A fee carries the same optional FX snapshot as a manual expense (ADR-148, ADR-149):
    when the client stamps ``fx_rate`` + ``fx_source`` the handler materializes the
    fee's ``usd_amount`` exactly like any expense (``round(amount ÷ fx_rate, 2)``); a
    fee sent without a snapshot stays null-snapshot, never rejected (ADR-031).

    Attributes:
        account_id: The account the fee is charged to; must belong to the caller.
        amount: The positive fee magnitude in the account's native currency (ADR-025).
        label: The human label used as the fee expense's ``name`` (e.g. "Deel fee").
        fx_rate: The ARS-per-1-USD rate the client captured for the fee, else ``None``
            (ADR-149). When positive the handler materializes the fee's ``usd_amount``.
        fx_source: Provenance of the fee's FX snapshot rate (e.g. ``'bolsa'``,
            ``'mep'``), else ``None`` (ADR-148).
    """

    account_id: UUID
    amount: Decimal = Field(gt=Decimal(0))
    label: str = Field(min_length=1)
    fx_rate: Decimal | None = None
    fx_source: str | None = None


class CreateTransfer(Command):
    """Request to record a transfer between two of the caller's accounts (ADR-135, ADR-130).

    The handler verifies both accounts (and every fee account) belong to the caller
    (ADR-130), generates ``id`` and timestamps, builds the aggregate through the
    domain so invariants run (``from != to``, positive legs, ADR-031), then creates
    one expense transaction per fee in the "Fees" category — all in one unit of work
    (ADR-135). ``amount_out`` is source-native, ``amount_in`` is destination-native;
    callers pass them equal for a same-currency transfer (ADR-135).
    """

    user_id: str
    from_account_id: UUID
    to_account_id: UUID
    amount_out: Decimal = Field(gt=Decimal(0))
    amount_in: Decimal = Field(gt=Decimal(0))
    occurred_on: date
    note: str | None = None
    fees: tuple[TransferFeeInput, ...] = ()


class DeleteTransfer(Command):
    """Request to delete a transfer by identity (ADR-135, ADR-130).

    ``user_id`` is the authenticated owner the entrypoint sets before dispatch; the
    handler scopes the delete by it so a cross-tenant delete removes nothing and
    surfaces a not-found (404, ADR-111). Deleting a transfer does NOT delete the fee
    expenses it created — they are independent expenses (ADR-135).
    """

    id: UUID
    user_id: str
